Hierodule: Static
Static
USART Module
Elements of the module that are confined to the scope of the compilation unit. Perfectly corresponds to the module's source file, except the IRQ handlers.
Functions
uint8_t ReceiveByte (HIERODULE_USART_Wrapper *Wrapper)
Reads and returns a single byte received by the USART peripheral.
void USART_IRQHandler (HIERODULE_USART_Wrapper *Wrapper)
The base IRQ body to be used for all USART IRQs.
Variables
HIERODULE_USART_Wrapper * USART1_Wrapper = NULL
USART wrapper pointer meant for USART1.
HIERODULE_USART_Wrapper * USART2_Wrapper = NULL
USART wrapper pointer meant for USART2.
Requires the device specific macro __STM32F103xB_H or __STM32F401xC_H to be defined.
HIERODULE_USART_Wrapper * USART3_Wrapper = NULL
USART wrapper pointer meant for USART3.
Requires the device specific macro __STM32F103xB_H to be defined.
HIERODULE_USART_Wrapper * USART6_Wrapper = NULL
USART wrapper pointer meant for USART6.
Requires the device specific macro __STM32F401xC_H to be defined.
Detailed Description
Implements the routines defined in the header file and routines necessary for those in the background. Pointers of USART wrappers are also defined here.
IRQ definitions with custom ISR implementations are also included at the end of the file.
Function Documentation
ReceiveByte()
uint8_t ReceiveByte (HIERODULE_USART_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the USART wrapper.
Returns
Byte read from RDR.
Meant to be used in IRQ bodies and not for custom implementations, hence the reason it's static.
Definition at line 64 of file hierodule_usart.c.
 {
     #ifdef __STM32F030x6_H
     return (uint8_t)(READ_BIT(Wrapper->USART->RDR, USART_RDR_RDR));
     #else
     return (uint8_t)(READ_BIT(Wrapper->USART->DR, USART_DR_DR));
     #endif
 }
References HIERODULE_USART_Wrapper::USART.
Referenced by USART_IRQHandler().
USART_IRQHandler()
void USART_IRQHandler (HIERODULE_USART_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the USART wrapper.
Returns
None
Byte received in the RDR is not handled if the ISR has not been assigned.
If the wrapper is indeed assigned, the received byte is loaded at the next index of the ring buffer and the ISR HIERODULE_USART_Wrapper::RX_Handler is called if it's not NULL.
Definition at line 322 of file hierodule_usart.c.
 {
     if( HIERODULE_USART_IsActiveFlag_RXNE(Wrapper) )
     {
         if(Wrapper != NULL)
         {
             Wrapper->RX_Buffer[Wrapper->RX_Index] =
             ReceiveByte(Wrapper);
             Wrapper->RX_Index++;
             Wrapper->RX_Index %= Wrapper->RX_BufferSize;
             if( Wrapper->RX_New < Wrapper->RX_BufferSize )
                 Wrapper->RX_New++;
             if(Wrapper->RX_Handler != NULL)
             {
                 Wrapper->RX_Handler
                 (
                     HIERODULE_USART_GetNextByte(Wrapper)
                 );
             }
         }
     }
 }
References HIERODULE_USART_GetNextByte(), HIERODULE_USART_IsActiveFlag_RXNE(), ReceiveByte(), HIERODULE_USART_Wrapper::RX_Buffer, HIERODULE_USART_Wrapper::RX_BufferSize, HIERODULE_USART_Wrapper::RX_Handler, HIERODULE_USART_Wrapper::RX_Index, and HIERODULE_USART_Wrapper::RX_New.
Referenced by USART1_IRQHandler(), USART2_IRQHandler(), USART3_IRQHandler(), and USART6_IRQHandler().
Variable Documentation
USART1_Wrapper
HIERODULE_USART_Wrapper* USART1_Wrapper = NULL
Definition at line 29 of file hierodule_usart.c.
Referenced by HIERODULE_USART_InitWrapper(), and USART1_IRQHandler().
USART2_Wrapper
HIERODULE_USART_Wrapper* USART2_Wrapper = NULL
Definition at line 36 of file hierodule_usart.c.
Referenced by HIERODULE_USART_InitWrapper(), and USART2_IRQHandler().
USART3_Wrapper
HIERODULE_USART_Wrapper* USART3_Wrapper = NULL
Definition at line 45 of file hierodule_usart.c.
Referenced by HIERODULE_USART_InitWrapper(), and USART3_IRQHandler().
USART6_Wrapper
HIERODULE_USART_Wrapper* USART6_Wrapper = NULL
Definition at line 54 of file hierodule_usart.c.
Referenced by HIERODULE_USART_InitWrapper(), and USART6_IRQHandler().