Hierodule: Global
Global
ADC Module
Elements of the module that are not confined to the scope of the compilation unit. Perfectly corresponds to the module's header file, except the IRQ handlers.
Data Structures
struct HIERODULE_ADC_Wrapper
Struct that keeps variables for the ADC data, a pointer to the ADC peripheral and a pointer to the ISR for EOC.
Macros
#define HIERODULE_ADC_SMOOTHENING_FILTER
Precompiler constant to toggle ADC smoothing filter.
Functions
HIERODULE_ADC_Wrapper ** HIERODULE_ADC_InitWrapper (ADC_TypeDef *_ADC, void(*ISR)(uint16_t))
Initializes a wrapper for the specified ADC peripheral.
void HIERODULE_ADC_ReleaseWrapper (HIERODULE_ADC_Wrapper *Wrapper)
Frees the memory allocated to an ADC wrapper.
void HIERODULE_ADC_Enable (HIERODULE_ADC_Wrapper *Wrapper)
Updates relevant control register bits to start ADC action.
void HIERODULE_ADC_Disable (HIERODULE_ADC_Wrapper *Wrapper)
Updates relevant control register bits to stop ADC action.
void ADC1_2_IRQHandler (void)
ADC1_2 IRQ implementation.
Requires the device specific macro __STM32F103xB_H to be defined.
void ADC_IRQHandler (void)
ADC IRQ implementation.
Requires the device specific macro __STM32F401xC_H to be defined.
void ADC1_IRQHandler (void)
ADC1 IRQ implementation.
Requires the device specific macro __STM32F030x6_H to be defined.
Detailed Description
Consists of basic ADC peripheral handler routines and an ADC Wrapper struct, as well as an initializer for it.
Device-specific macro constants and type definitions are imported with an include directive to main.h, where the device driver headers are assumed to be included.
stdlib.h also included for malloc.
Macro Definition Documentation
HIERODULE_ADC_SMOOTHENING_FILTER
#define HIERODULE_ADC_SMOOTHENING_FILTER
When commented out, filter relevant variables and functions won't be compiled and received data won't be filtered.
Definition at line 38 of file hierodule_adc.h.
Function Documentation
ADC1_2_IRQHandler()
void ADC1_2_IRQHandler (void)
Returns
None
If the wrapper to an ADC peripheral is allocated and flag checks are true, data holder in the assigned wrapper gets updated. If the wrapper has an ISR assigned, that is also invoked.
Notice the filter is optional.
Definition at line 176 of file hierodule_adc.c.
 {
     if(ADC1_Wrapper != NULL)
     {
         if (READ_BIT(ADC1_Wrapper->_ADC->CR1, ADC_CR1_EOCIE) == (ADC_CR1_EOCIE))
         {
             if (READ_BIT(ADC1_Wrapper->_ADC->SR, ADC_SR_EOC) == (ADC_SR_EOC))
             {
                 #ifdef HIERODULE_ADC_SMOOTHENING_FILTER
                 Smoothen(ADC1_Wrapper);
                 #else
                 ADC1_Wrapper->Data = ADC1_Wrapper->_ADC->DR;
                 #endif
                 if(ADC1_Wrapper->Data_Handler != NULL)
                 {
                     ADC1_Wrapper->Data_Handler(ADC1_Wrapper->Data);
                 }
             }
         }
     }
     if(ADC2_Wrapper != NULL)
     {
         if (READ_BIT(ADC2_Wrapper->_ADC->CR1, ADC_CR1_EOCIE) == (ADC_CR1_EOCIE))
         {
             if (READ_BIT(ADC2_Wrapper->_ADC->SR, ADC_SR_EOC) == (ADC_SR_EOC))
             {
                 #ifdef HIERODULE_ADC_SMOOTHENING_FILTER
                 Smoothen(ADC2_Wrapper);
                 #else
                 ADC2_Wrapper->Data = ADC2_Wrapper->_ADC->DR;
                 #endif
                 if(ADC2_Wrapper->Data_Handler != NULL)
                 {
                     ADC2_Wrapper->Data_Handler(ADC2_Wrapper->Data);
                 }
             }
         }
     }
 }
References HIERODULE_ADC_Wrapper::_ADC, ADC1_Wrapper, ADC2_Wrapper, HIERODULE_ADC_Wrapper::Data, HIERODULE_ADC_Wrapper::Data_Handler, and Smoothen().
ADC1_IRQHandler()
void ADC1_IRQHandler (void)
Returns
None
If the wrapper to an ADC peripheral is allocated and flag checks are true, data holder in the assigned wrapper gets updated. If the wrapper has an ISR assigned, that is also invoked.
Notice the filter is optional.
Definition at line 267 of file hierodule_adc.c.
 {
     if(ADC1_Wrapper != NULL)
     {
         if (READ_BIT(ADC1_Wrapper->_ADC->IER, ADC_IER_EOCIE) == (ADC_IER_EOCIE))
         {
             if (READ_BIT(ADC1_Wrapper->_ADC->ISR, ADC_ISR_EOC) == (ADC_ISR_EOC))
             {
                 #ifdef HIERODULE_ADC_SMOOTHENING_FILTER
                 Smoothen(ADC1_Wrapper);
                 #else
                 ADC1_Wrapper->Data = ADC1_Wrapper->_ADC->DR;
                 #endif
                 if(ADC1_Wrapper->Data_Handler != NULL)
                 {
                     ADC1_Wrapper->Data_Handler(ADC1_Wrapper->Data);
                 }
             }
         }
     }
 }
References HIERODULE_ADC_Wrapper::_ADC, ADC1_Wrapper, HIERODULE_ADC_Wrapper::Data, HIERODULE_ADC_Wrapper::Data_Handler, and Smoothen().
ADC_IRQHandler()
void ADC_IRQHandler (void)
Returns
None
If the wrapper to an ADC peripheral is allocated and flag checks are true, data holder in the assigned wrapper gets updated. If the wrapper has an ISR assigned, that is also invoked.
Notice the filter is optional.
Definition at line 233 of file hierodule_adc.c.
 {
     if(ADC1_Wrapper != NULL)
     {
         if (READ_BIT(ADC1_Wrapper->_ADC->CR1, ADC_CR1_EOCIE) == (ADC_CR1_EOCIE))
         {
             if (READ_BIT(ADC1_Wrapper->_ADC->SR, ADC_SR_EOC) == (ADC_SR_EOC))
             {
                 #ifdef HIERODULE_ADC_SMOOTHENING_FILTER
                 Smoothen(ADC1_Wrapper);
                 #else
                 ADC1_Wrapper->Data = ADC1_Wrapper->_ADC->DR;
                 #endif
                 if(ADC1_Wrapper->Data_Handler != NULL)
                 {
                     ADC1_Wrapper->Data_Handler(ADC1_Wrapper->Data);
                 }
             }
         }
     }
 }
References HIERODULE_ADC_Wrapper::_ADC, ADC1_Wrapper, HIERODULE_ADC_Wrapper::Data, HIERODULE_ADC_Wrapper::Data_Handler, and Smoothen().
HIERODULE_ADC_Disable()
void HIERODULE_ADC_Disable (HIERODULE_ADC_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the ADC wrapper.
Returns
None
Self-explanatory code, nothing to elaborate.
Definition at line 146 of file hierodule_adc.c.
 {
     #if ( (defined __STM32F103xB_H) || (defined __STM32F401xC_H) )
     CLEAR_BIT(Wrapper->_ADC->CR1, ADC_CR1_EOCIE);
     CLEAR_BIT(Wrapper->_ADC->CR2, ADC_CR2_ADON);
     #ifdef __STM32F103xB_H
     CLEAR_BIT(Wrapper->_ADC->CR2, (ADC_CR2_SWSTART | ADC_CR2_EXTTRIG));
     #elif defined __STM32F401xC_H
     CLEAR_BIT(Wrapper->_ADC->CR2, ADC_CR2_SWSTART);
     #endif
     #elif defined __STM32F030x6_H
     SET_BIT(Wrapper->_ADC->CR, ADC_CR_ADDIS);
     SET_BIT(Wrapper->_ADC->CR, ADC_CR_ADSTP);
     #endif
 }
References HIERODULE_ADC_Wrapper::_ADC.
Referenced by HIERODULE_ADC_ReleaseWrapper().
HIERODULE_ADC_Enable()
void HIERODULE_ADC_Enable (HIERODULE_ADC_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the ADC wrapper.
Returns
None
Self-explanatory code, nothing to elaborate.
Definition at line 118 of file hierodule_adc.c.
 {
     #if ( (defined __STM32F103xB_H) || (defined __STM32F401xC_H) )
     SET_BIT(Wrapper->_ADC->CR1, ADC_CR1_EOCIE);
     CLEAR_BIT(Wrapper->_ADC->SR, ADC_SR_EOC);
     SET_BIT(Wrapper->_ADC->CR2, ADC_CR2_ADON);
     #ifdef __STM32F103xB_H
     SET_BIT(Wrapper->_ADC->CR2, (ADC_CR2_SWSTART | ADC_CR2_EXTTRIG));
     #elif defined __STM32F401xC_H
     SET_BIT(Wrapper->_ADC->CR2, ADC_CR2_SWSTART);
     #endif
     #elif defined __STM32F030x6_H
     SET_BIT(Wrapper->_ADC->IER, ADC_IER_EOCIE);
     CLEAR_BIT(Wrapper->_ADC->ISR, ADC_ISR_EOC);
     SET_BIT(Wrapper->_ADC->CR, ADC_CR_ADEN);
     SET_BIT(Wrapper->_ADC->CR, ADC_CR_ADSTART);
     #endif
 }
References HIERODULE_ADC_Wrapper::_ADC.
HIERODULE_ADC_InitWrapper()
HIERODULE_ADC_Wrapper ** HIERODULE_ADC_InitWrapper (ADC_TypeDef * _ADC, void(*)(uint16_t) ISR)
Parameters
_ADC ADC peripheral of the wrapper.
ISR Pointer to the ISR for EOC.
Returns
Double pointer to the initialized wrapper.
Smoothening filter weight is initially set to 0.5, which may be changed during the wrapper's lifetime.
The wrapper pointer gets a new address allocated, to be freed at some future point via HIERODULE_ADC_ReleaseWrapper, hence the reason a pointer is used for the wrapper; likewise, a double pointer is used to return it by reference.
Device specific checks are performed for the ADC peripheral specified.
Definition at line 67 of file hierodule_adc.c.
 {
     HIERODULE_ADC_Wrapper **Wrapper;
     uint32_t ADC_Address = (uint32_t)_ADC;
     switch(ADC_Address)
     {
         case ( (uint32_t)ADC1 ):
             Wrapper = &ADC1_Wrapper;
             break;
         #ifdef __STM32F103xB_H
         case ( (uint32_t)ADC2 ):
             Wrapper = &ADC2_Wrapper;
             break;
         #endif
         default:
             return NULL;
             break;
     }
     (*Wrapper) = (HIERODULE_ADC_Wrapper*)malloc(sizeof(HIERODULE_ADC_Wrapper));
     (*Wrapper)->_ADC = _ADC;
     (*Wrapper)->Data = 0;
     #ifdef HIERODULE_ADC_SMOOTHENING_FILTER
     (*Wrapper)->FilterWeight = 0.5;
     #endif
     (*Wrapper)->Data_Handler = ISR;
     return Wrapper;
 }
References HIERODULE_ADC_Wrapper::_ADC, ADC1_Wrapper, and ADC2_Wrapper.
HIERODULE_ADC_ReleaseWrapper()
void HIERODULE_ADC_ReleaseWrapper (HIERODULE_ADC_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the ADC wrapper.
Returns
None
Using a released ADC wrapper or its fields may result in unexpected behavior.
Keep in mind this clears up the ADC wrapper pointer in this file scope; it is recommended to free your double pointer to the wrapper, likewise.
Definition at line 108 of file hierodule_adc.c.
 {
     HIERODULE_ADC_Disable(Wrapper);
     free(Wrapper);
     Wrapper = NULL;
 }
References HIERODULE_ADC_Disable().