Hierodule: Static
Static
I2C Module
Elements of the module that are confined to the scope of the compilation unit. Perfectly corresponds to the module's source file, except the IRQ handlers.
Functions
void Idle (HIERODULE_I2C_Wrapper *Wrapper, uint32_t NumberOfPeriods)
Blocks for given number of I2C clock periods.
void EnableClockStretching (HIERODULE_I2C_Wrapper *Wrapper)
Enables clock stretching for the I2C peripheral of a wrapper.
void DisableClockStretching (HIERODULE_I2C_Wrapper *Wrapper)
Disables clock stretching for the I2C peripheral of a wrapper.
static uint8_t ReceiveData (HIERODULE_I2C_Wrapper *Wrapper)
Read and returns the data register content of the I2C peripheral.
void TransmitData (HIERODULE_I2C_Wrapper *Wrapper, uint8_t Byte)
Writes a byte into the data register of the I2C peripheral.
void ACK_Next (HIERODULE_I2C_Wrapper *Wrapper)
Configure the I2C peripheral to "ACK" the next byte received.
void NACK_Next (HIERODULE_I2C_Wrapper *Wrapper)
Configure the I2C peripheral to "NACK" the next byte received.
void Start (HIERODULE_I2C_Wrapper *Wrapper)
Makes the I2C peripheral generate a start condition.
void Stop (HIERODULE_I2C_Wrapper *Wrapper)
Makes the I2C peripheral generate a stop condition.
void ReceiveByteAsMaster (HIERODULE_I2C_Wrapper *Wrapper)
Handles incoming data for an I2C peripheral in master receiver mode.
void ReceiveByteAsSlave (HIERODULE_I2C_Wrapper *Wrapper)
Handles incoming data for an I2C peripheral in slave receiver mode.
void TransmitByteAsMaster (HIERODULE_I2C_Wrapper *Wrapper)
Transmits the next data in the buffer for an I2C peripheral in master transmitter mode.
void TransmitByteAsSlave (HIERODULE_I2C_Wrapper *Wrapper)
Transmits the next data in the buffer for an I2C peripheral in slave transmitter mode.
void ReturnToIdleState (HIERODULE_I2C_Wrapper *Wrapper)
Invokes the on-SRX-finished routine if assigned and sets the I2C wrapper status back to idle.
void Receive_NACK (HIERODULE_I2C_Wrapper *Wrapper)
Receives the NACK response, invokes the on-SRX-finished routine and sets the wrapper status back to idle.
void I2C_IRQ_Handler (HIERODULE_I2C_Wrapper *Wrapper)
The base IRQ body to be used for all I2C IRQs.
Variables
static HIERODULE_I2C_Wrapper * I2C1_Wrapper
I2C wrapper pointer meant for I2C1.
static HIERODULE_I2C_Wrapper * I2C2_Wrapper
I2C wrapper pointer meant for I2C2.
Requires the device specific macro __STM32F103xB_H or __STM32F401xC_H to be defined.
static HIERODULE_I2C_Wrapper * I2C3_Wrapper
I2C wrapper pointer meant for I2C3.
Requires the device specific macro __STM32F401xC_H to be defined.
Detailed Description
Implements the routines defined in the header file and routines necessary for those in the background. Pointers of I2C wrappers are also defined here.
IRQ definitions with custom ISR implementations are also included at the end of the file.
Function Documentation
ACK_Next()
void ACK_Next (HIERODULE_I2C_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
None
Self-explanatory code, nothing to elaborate.
Definition at line 157 of file hierodule_i2c.c.
 {
     #ifndef __STM32F030x6_H
     MODIFY_REG(Wrapper->_I2C->CR1, I2C_CR1_ACK, I2C_CR1_ACK);
     #else
     MODIFY_REG(Wrapper->_I2C->CR2, I2C_CR2_NACK, 0);
     #endif
 }
References HIERODULE_I2C_Wrapper::_I2C.
Referenced by HIERODULE_I2C_InitWrapper(), and ReceiveByteAsMaster().
DisableClockStretching()
void DisableClockStretching (HIERODULE_I2C_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
None
Self-explanatory code, nothing to elaborate.
Definition at line 94 of file hierodule_i2c.c.
 {
     #ifdef __STM32F030x6_H
     CLEAR_BIT(Wrapper->_I2C->CR1, I2C_CR1_PE);
     while( 1 == (READ_BIT(Wrapper->_I2C->CR1, I2C_CR1_PE) == (I2C_CR1_PE)) );
     #endif
     SET_BIT(Wrapper->_I2C->CR1, I2C_CR1_NOSTRETCH);
     while( 1 == (READ_BIT(Wrapper->_I2C->CR1, I2C_CR1_NOSTRETCH) != (I2C_CR1_NOSTRETCH)) );
     #ifdef __STM32F030x6_H
     SET_BIT(Wrapper->_I2C->CR1, I2C_CR1_PE);
     while( 0 == (READ_BIT(Wrapper->_I2C->CR1, I2C_CR1_PE) == (I2C_CR1_PE)) );
     #endif
 }
References HIERODULE_I2C_Wrapper::_I2C.
Referenced by HIERODULE_I2C_MasterReceive(), and HIERODULE_I2C_MasterTransmit().
EnableClockStretching()
void EnableClockStretching (HIERODULE_I2C_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
None
Self-explanatory code, nothing to elaborate.
Definition at line 68 of file hierodule_i2c.c.
 {
     #ifdef __STM32F030x6_H
     CLEAR_BIT(Wrapper->_I2C->CR1, I2C_CR1_PE);
     while( 1 == (READ_BIT(Wrapper->_I2C->CR1, I2C_CR1_PE) == (I2C_CR1_PE)) );
     #endif
     CLEAR_BIT(Wrapper->_I2C->CR1, I2C_CR1_NOSTRETCH);
     while( 0 == (READ_BIT(Wrapper->_I2C->CR1, I2C_CR1_NOSTRETCH) != (I2C_CR1_NOSTRETCH)) );
     #ifdef __STM32F030x6_H
     SET_BIT(Wrapper->_I2C->CR1, I2C_CR1_PE);
     while( 0 == (READ_BIT(Wrapper->_I2C->CR1, I2C_CR1_PE) == (I2C_CR1_PE)) );
     #endif
 }
References HIERODULE_I2C_Wrapper::_I2C.
Referenced by HIERODULE_I2C_InitWrapper(), ReceiveByteAsMaster(), and TransmitByteAsMaster().
I2C_IRQ_Handler()
void I2C_IRQ_Handler (HIERODULE_I2C_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
None
Transmission control is performed by handling the interrupt flags in accordance to the wrapper's status.
Definition at line 629 of file hierodule_i2c.c.
 {
     #ifndef __STM32F030x6_H
     uint8_t _ADDR_Active = (READ_BIT(Wrapper->_I2C->SR1, I2C_SR1_ADDR) == (I2C_SR1_ADDR));
     #else
     uint8_t _ADDR_Active = (READ_BIT(Wrapper->_I2C->ISR, I2C_ISR_ADDR) == (I2C_ISR_ADDR));
     #endif
     #ifdef __STM32F030x6_H
     if ( READ_BIT(Wrapper->_I2C->ISR, I2C_ISR_NACKF) == (I2C_ISR_NACKF) )
     {
         Receive_NACK(Wrapper);
     }
     #else
     if ( READ_BIT(Wrapper->_I2C->SR1, I2C_SR1_AF) == (I2C_SR1_AF) )
     {
         Receive_NACK(Wrapper);
     }
     #endif
     #ifdef __STM32F030x6_H
     else if( READ_BIT(Wrapper->_I2C->ISR, I2C_ISR_RXNE) == (I2C_ISR_RXNE) )
     {
         if( Wrapper->Status == HIERODULE_I2C_Status_MRX )
             ReceiveByteAsMaster(Wrapper);
         else
         {
             if( Wrapper->Status == HIERODULE_I2C_Status_SRX )
                 ReceiveByteAsSlave(Wrapper);
             else
                 ReceiveData(Wrapper);
         }
     }
     #else
     else if( READ_BIT(Wrapper->_I2C->SR1, I2C_SR1_RXNE) == (I2C_SR1_RXNE) )
     {
         if( Wrapper->Status == HIERODULE_I2C_Status_MRX )
             ReceiveByteAsMaster(Wrapper);
         else
         {
             if( Wrapper->Status == HIERODULE_I2C_Status_SRX )
                 ReceiveByteAsSlave(Wrapper);
             else
                 ReceiveData(Wrapper);
         }
     }
     #endif
     #ifndef __STM32F030x6_H
     else if ( READ_BIT(Wrapper->_I2C->SR1, I2C_SR1_SB) == (I2C_SR1_SB) )
     {
         if( Wrapper->Status == HIERODULE_I2C_Status_MTX_SB )
             Wrapper->Status = HIERODULE_I2C_Status_MTX_ADR;
         else if( Wrapper->Status == HIERODULE_I2C_Status_MRX_SB )
             Wrapper->Status = HIERODULE_I2C_Status_MRX_ADR;
         TransmitData(Wrapper, Wrapper->SlaveAddress);
     }
     #endif
     else if ( _ADDR_Active )
     {
         if(Wrapper->Status == HIERODULE_I2C_Status_IDLE)
         {
             #ifndef __STM32F030x6_H
             uint32_t _t_dir = (uint32_t)(READ_BIT(Wrapper->_I2C->SR2, I2C_SR2_TRA));
             #else
             uint32_t _t_dir = (uint32_t)(READ_BIT(Wrapper->_I2C->ISR, I2C_ISR_DIR));
             #endif
             if( 0 == _t_dir )
                 Wrapper->Status = HIERODULE_I2C_Status_SRX;
             else
                 Wrapper->Status = HIERODULE_I2C_Status_STX;
         }
         #ifndef __STM32F030x6_H
         else if(Wrapper->Status == HIERODULE_I2C_Status_MTX_ADR)
         {
             Wrapper->Status = HIERODULE_I2C_Status_MTX;
         }
         else if(Wrapper->Status == HIERODULE_I2C_Status_MRX_ADR)
         {
             Wrapper->Status = HIERODULE_I2C_Status_MRX;
         }
         READ_REG(Wrapper->_I2C->SR1);
         READ_REG(Wrapper->_I2C->SR2);
         #else
         SET_BIT(Wrapper->_I2C->ICR, I2C_ICR_ADDRCF);
         #endif
     }
     #ifndef __STM32F030x6_H
     else if ( (READ_BIT(Wrapper->_I2C->SR1, I2C_SR1_TXE) == (I2C_SR1_TXE)) )
     {
         if(Wrapper->Status == HIERODULE_I2C_Status_MTX )
         {
             TransmitByteAsMaster(Wrapper);
         }
         else if(Wrapper->Status == HIERODULE_I2C_Status_STX )
         {
             TransmitByteAsSlave(Wrapper);
             while(READ_BIT(Wrapper->_I2C->SR1, I2C_SR1_TXE) != (I2C_SR1_TXE))
             {
                 if ( READ_BIT(Wrapper->_I2C->SR1, I2C_SR1_AF) == (I2C_SR1_AF) )
                 {
                     Receive_NACK(Wrapper);
                     break;
                 }
             }
         }
     }
     #else
     else if ( READ_BIT(Wrapper->_I2C->ISR, I2C_ISR_TXIS) == (I2C_ISR_TXIS) )
     {
         if(Wrapper->Status == HIERODULE_I2C_Status_MTX )
         {
             TransmitByteAsMaster(Wrapper);
         }
         else if(Wrapper->Status == HIERODULE_I2C_Status_STX )
         {
             TransmitByteAsSlave(Wrapper);
             while( READ_BIT(Wrapper->_I2C->ISR, I2C_ISR_TXIS) != (I2C_ISR_TXIS) )
             {
                 if ( READ_BIT(Wrapper->_I2C->ISR, I2C_ISR_NACKF) == (I2C_ISR_NACKF) )
                 {
                     Receive_NACK(Wrapper);
                     break;
                 }
             }
         }
     }
     #endif
     #ifdef __STM32F030x6_H
     else if ( READ_BIT(Wrapper->_I2C->ISR, I2C_ISR_STOPF) == (I2C_ISR_STOPF) )
     {
         ReturnToIdleState(Wrapper);
     }
     #else
     else if ( READ_BIT(Wrapper->_I2C->SR1, I2C_SR1_STOPF) == (I2C_SR1_STOPF) )
     {
         ReturnToIdleState(Wrapper);
     }
     #endif
 }
References HIERODULE_I2C_Wrapper::_I2C, HIERODULE_I2C_Status_IDLE, HIERODULE_I2C_Status_MRX, HIERODULE_I2C_Status_MRX_ADR, HIERODULE_I2C_Status_MRX_SB, HIERODULE_I2C_Status_MTX, HIERODULE_I2C_Status_MTX_ADR, HIERODULE_I2C_Status_MTX_SB, HIERODULE_I2C_Status_SRX, HIERODULE_I2C_Status_STX, Receive_NACK(), ReceiveByteAsMaster(), ReceiveByteAsSlave(), ReceiveData(), ReturnToIdleState(), HIERODULE_I2C_Wrapper::SlaveAddress, HIERODULE_I2C_Wrapper::Status, TransmitByteAsMaster(), TransmitByteAsSlave(), and TransmitData().
Referenced by I2C1_EV_IRQHandler(), I2C1_IRQHandler(), I2C2_EV_IRQHandler(), and I2C3_EV_IRQHandler().
Idle()
void Idle (HIERODULE_I2C_Wrapper * Wrapper, uint32_t NumberOfPeriods)
Parameters
Wrapper Pointer to the I2C wrapper.
NumberOfPeriods Number of I2C clock periods.
Returns
None
The period length is calculated beforehand with a HIERODULE_I2C_InitWrapper call.
Definition at line 55 of file hierodule_i2c.c.
 {
     for(uint32_t i = 0 ; i < Wrapper->I2C_Period_Length*NumberOfPeriods ; i++)
     {
         __NOP();
     }
 }
References HIERODULE_I2C_Wrapper::I2C_Period_Length.
Referenced by TransmitByteAsSlave().
NACK_Next()
void NACK_Next (HIERODULE_I2C_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
None
Self-explanatory code, nothing to elaborate.
Definition at line 174 of file hierodule_i2c.c.
 {
     #ifndef __STM32F030x6_H
     MODIFY_REG(Wrapper->_I2C->CR1, I2C_CR1_ACK, 0);
     #else
     MODIFY_REG(Wrapper->_I2C->CR2, I2C_CR2_NACK, I2C_CR2_NACK);
     #endif
 }
References HIERODULE_I2C_Wrapper::_I2C.
Referenced by HIERODULE_I2C_MasterReceive(), and ReceiveByteAsMaster().
Receive_NACK()
void Receive_NACK (HIERODULE_I2C_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
None
Only to be used when exiting slave transmitter mode.
Definition at line 355 of file hierodule_i2c.c.
 {
     if(Wrapper->Status == HIERODULE_I2C_Status_STX )
     {
         #ifdef __STM32F030x6_H
         SET_BIT(Wrapper->_I2C->ICR, I2C_ICR_NACKCF);
         while( 1 == READ_BIT(Wrapper->_I2C->ISR, I2C_ISR_NACKF) );
         #else
         CLEAR_BIT(Wrapper->_I2C->SR1, I2C_SR1_AF);
         #endif
         #ifdef __STM32F030x6_H
         TransmitByteAsSlave(Wrapper);
         while( 0 == READ_BIT(Wrapper->_I2C->ISR, I2C_ISR_STOPF) );
         SET_BIT(Wrapper->_I2C->ICR, I2C_ICR_STOPCF);
         while( 1 == READ_BIT(Wrapper->_I2C->ISR, I2C_ISR_STOPF) );
         #endif
         if( Wrapper->STX_Handler != NULL)
             Wrapper->STX_Handler();
         Wrapper->Status = HIERODULE_I2C_Status_IDLE;
     }
 }
References HIERODULE_I2C_Wrapper::_I2C, HIERODULE_I2C_Status_IDLE, HIERODULE_I2C_Status_STX, HIERODULE_I2C_Wrapper::Status, HIERODULE_I2C_Wrapper::STX_Handler, and TransmitByteAsSlave().
Referenced by I2C_IRQ_Handler().
ReceiveByteAsMaster()
void ReceiveByteAsMaster (HIERODULE_I2C_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
None
The received byte is appended to the MRX buffer of the wrapper.
The data is "ACKed" or "NACKed", depending on whether it's the last byte the master expects to receive. The wrapper is returned to the idle state in the latter case and depending on the device, clock stretching is enabled back again.
Definition at line 229 of file hierodule_i2c.c.
 {
     (Wrapper->MRX_Buffer)[Wrapper->MRX_Counter] =
     ReceiveData(Wrapper);
     Wrapper->MRX_Counter++;
     if(Wrapper->MRX_Counter == Wrapper->MRX_BufferSize)
     {
         Wrapper->Status = HIERODULE_I2C_Status_IDLE;
         Wrapper->SlaveAddress = 0;
         Stop(Wrapper);
         #ifndef __STM32F030x6_H
         EnableClockStretching(Wrapper);
         #endif
         ACK_Next(Wrapper);
         if( Wrapper->MRX_Handler != NULL)
             Wrapper->MRX_Handler();
     }
     else if(Wrapper->MRX_Counter == Wrapper->MRX_BufferSize-1)
     {
         NACK_Next(Wrapper);
         __NOP();
     }
 }
References ACK_Next(), EnableClockStretching(), HIERODULE_I2C_Status_IDLE, HIERODULE_I2C_Wrapper::MRX_Buffer, HIERODULE_I2C_Wrapper::MRX_BufferSize, HIERODULE_I2C_Wrapper::MRX_Counter, HIERODULE_I2C_Wrapper::MRX_Handler, NACK_Next(), ReceiveData(), HIERODULE_I2C_Wrapper::SlaveAddress, HIERODULE_I2C_Wrapper::Status, and Stop().
Referenced by I2C_IRQ_Handler().
ReceiveByteAsSlave()
void ReceiveByteAsSlave (HIERODULE_I2C_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
None
The routine is stateless, assuming the wrapper status handling is performed accordingly.
Definition at line 266 of file hierodule_i2c.c.
 {
     Wrapper->SRX_Buffer[Wrapper->SRX_Index] =
     ReceiveData(Wrapper);
     Wrapper->SRX_Index++;
     Wrapper->SRX_Index %= Wrapper->SRX_BufferSize;
     if( Wrapper->SRX_New < Wrapper->SRX_BufferSize )
         Wrapper->SRX_New++;
 }
References ReceiveData(), HIERODULE_I2C_Wrapper::SRX_Buffer, HIERODULE_I2C_Wrapper::SRX_BufferSize, HIERODULE_I2C_Wrapper::SRX_Index, and HIERODULE_I2C_Wrapper::SRX_New.
Referenced by I2C_IRQ_Handler().
ReceiveData()
static uint8_t ReceiveData (HIERODULE_I2C_Wrapper * Wrapper) static
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
uint8_t The byte returned.
Defined as static to avoid the multiple definition error some compilers throw since a function with the same name also exists within another module; that will be fixed in a future release.
Definition at line 122 of file hierodule_i2c.c.
 {
     #ifdef __STM32F030x6_H
     return (uint8_t)(READ_BIT(Wrapper->_I2C->RXDR, I2C_RXDR_RXDATA));
     #else
     return (uint8_t)(READ_BIT(Wrapper->_I2C->DR, I2C_DR_DR));
     #endif
 }
References HIERODULE_I2C_Wrapper::_I2C.
Referenced by I2C_IRQ_Handler(), ReceiveByteAsMaster(), and ReceiveByteAsSlave().
ReturnToIdleState()
void ReturnToIdleState (HIERODULE_I2C_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
None
Only to be used when exiting slave receiver mode.
Definition at line 334 of file hierodule_i2c.c.
 {
     #ifdef __STM32F030x6_H
     SET_BIT(Wrapper->_I2C->ICR, I2C_ICR_STOPCF);
     #else
     SET_BIT(Wrapper->_I2C->CR1, I2C_CR1_PE);
     #endif
     if( Wrapper->SRX_Handler != NULL)
         Wrapper->SRX_Handler();
     Wrapper->Status = HIERODULE_I2C_Status_IDLE;
 }
References HIERODULE_I2C_Wrapper::_I2C, HIERODULE_I2C_Status_IDLE, HIERODULE_I2C_Wrapper::SRX_Handler, and HIERODULE_I2C_Wrapper::Status.
Referenced by I2C_IRQ_Handler().
Start()
void Start (HIERODULE_I2C_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
None
Self-explanatory code, nothing to elaborate.
Definition at line 191 of file hierodule_i2c.c.
 {
     #ifndef __STM32F030x6_H
     SET_BIT(Wrapper->_I2C->CR1, I2C_CR1_START);
     #else
     SET_BIT(Wrapper->_I2C->CR2, I2C_CR2_START);
     #endif
 }
References HIERODULE_I2C_Wrapper::_I2C.
Referenced by HIERODULE_I2C_MasterReceive(), and HIERODULE_I2C_MasterTransmit().
Stop()
void Stop (HIERODULE_I2C_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
None
Self-explanatory code, nothing to elaborate.
Definition at line 208 of file hierodule_i2c.c.
 {
     #ifndef __STM32F030x6_H
     SET_BIT(Wrapper->_I2C->CR1, I2C_CR1_STOP);
     #else
     SET_BIT(Wrapper->_I2C->CR2, I2C_CR2_STOP);
     #endif
 }
References HIERODULE_I2C_Wrapper::_I2C.
Referenced by ReceiveByteAsMaster(), and TransmitByteAsMaster().
TransmitByteAsMaster()
void TransmitByteAsMaster (HIERODULE_I2C_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
None
The MTX buffer should be set before initializing the transmission.
Definition at line 284 of file hierodule_i2c.c.
 {
     TransmitData(Wrapper, (Wrapper->MTX_Buffer)[Wrapper->MTX_Counter]);
     Wrapper->MTX_Counter++;
     if( Wrapper->MTX_Counter == Wrapper->MTX_BufferSize )
     {
         #ifndef __STM32F030x6_H
         while(READ_BIT(Wrapper->_I2C->SR1, I2C_SR1_TXE) != (I2C_SR1_TXE))
         #else
         while(READ_BIT(Wrapper->_I2C->ISR, I2C_ISR_TC) != (I2C_ISR_TC));
         #endif
         Wrapper->Status = HIERODULE_I2C_Status_IDLE;
         Wrapper->SlaveAddress = 0;
         Stop(Wrapper);
         #ifdef __STM32F030x6_H
         while( 0 == READ_BIT(Wrapper->_I2C->ISR, I2C_ISR_STOPF) );
         #endif
         EnableClockStretching(Wrapper);
         if( Wrapper->MTX_Handler != NULL)
             Wrapper->MTX_Handler();
     }
 }
References HIERODULE_I2C_Wrapper::_I2C, EnableClockStretching(), HIERODULE_I2C_Status_IDLE, HIERODULE_I2C_Wrapper::MTX_Buffer, HIERODULE_I2C_Wrapper::MTX_BufferSize, HIERODULE_I2C_Wrapper::MTX_Counter, HIERODULE_I2C_Wrapper::MTX_Handler, HIERODULE_I2C_Wrapper::SlaveAddress, HIERODULE_I2C_Wrapper::Status, Stop(), and TransmitData().
Referenced by I2C_IRQ_Handler().
TransmitByteAsSlave()
void TransmitByteAsSlave (HIERODULE_I2C_Wrapper * Wrapper)
Parameters
Wrapper Pointer to the I2C wrapper.
Returns
None
The STX buffer should be set before initializing the transmission.
Definition at line 318 of file hierodule_i2c.c.
 {
     if( Wrapper->STX_Buffer != NULL )
         TransmitData(Wrapper, (Wrapper->STX_Buffer)[(Wrapper->STX_Counter)++]);
     else
         TransmitData(Wrapper, 0);
     Idle(Wrapper, 1);
 }
References Idle(), HIERODULE_I2C_Wrapper::STX_Buffer, HIERODULE_I2C_Wrapper::STX_Counter, and TransmitData().
Referenced by I2C_IRQ_Handler(), and Receive_NACK().
TransmitData()
void TransmitData (HIERODULE_I2C_Wrapper * Wrapper, uint8_t Byte)
Parameters
Wrapper Pointer to the I2C wrapper.
Byte Byte to be written into the data register.
Returns
None
Self-explanatory code, nothing to elaborate.
Definition at line 140 of file hierodule_i2c.c.
 {
     #ifdef __STM32F030x6_H
     WRITE_REG(Wrapper->_I2C->TXDR, Byte);
     #else
     MODIFY_REG(Wrapper->_I2C->DR, I2C_DR_DR, Byte);
     #endif
 }
References HIERODULE_I2C_Wrapper::_I2C.
Referenced by I2C_IRQ_Handler(), TransmitByteAsMaster(), and TransmitByteAsSlave().
Variable Documentation
I2C1_Wrapper
HIERODULE_I2C_Wrapper* I2C1_Wrapper static
Definition at line 27 of file hierodule_i2c.c.
Referenced by HIERODULE_I2C_InitWrapper(), I2C1_EV_IRQHandler(), and I2C1_IRQHandler().
I2C2_Wrapper
HIERODULE_I2C_Wrapper* I2C2_Wrapper static
Definition at line 34 of file hierodule_i2c.c.
Referenced by HIERODULE_I2C_InitWrapper(), and I2C2_EV_IRQHandler().
I2C3_Wrapper
HIERODULE_I2C_Wrapper* I2C3_Wrapper static
Definition at line 44 of file hierodule_i2c.c.
Referenced by HIERODULE_I2C_InitWrapper(), and I2C3_EV_IRQHandler().