Hierodule: HIERODULE_ADC_Wrapper Struct Reference
HIERODULE_ADC_Wrapper Struct Reference
ADC Module » Global
Struct that keeps variables for the ADC data, a pointer to the ADC peripheral and a pointer to the ISR for EOC.
#include <hierodule_adc.h>
Data Fields
ADC_TypeDef * _ADC
Pointer to the ADC peripheral.
uint16_t Data
Variable to assign the received ADC data.
double FilterWeight
Filter weight for the smoothening filter.
void(* Data_Handler)(uint16_t)
Pointer to the ISR for EOC.
Detailed Description
Used by all routines in the module.
Alias typedefs for custom pointers are not defined, since they're not used excessively in the module.
Definition at line 46 of file hierodule_adc.h.
Field Documentation
_ADC
ADC_TypeDef* _ADC
This field is meant to be set via HIERODULE_ADC_InitWrapper, changing it manually may result in unexpected behavior.
Definition at line 51 of file hierodule_adc.h.
Referenced by ADC1_2_IRQHandler(), ADC1_IRQHandler(), and ADC_IRQHandler().
Data
uint16_t Data
This field is meant to be set via HIERODULE_ADC_InitWrapper, changing it manually may result in unexpected behavior.
Definition at line 55 of file hierodule_adc.h.
Referenced by ADC1_2_IRQHandler(), ADC1_IRQHandler(), and ADC_IRQHandler().
Data_Handler
void(* Data_Handler) (uint16_t)
Notice this points to a function with a uint16_t parameter, ergo the ISR assigned must be declared accordingly, even if it won't use the received byte in its definition.
Definition at line 67 of file hierodule_adc.h.
Referenced by ADC1_2_IRQHandler(), ADC1_IRQHandler(), and ADC_IRQHandler().
FilterWeight
double FilterWeight
Requires HIERODULE_ADC_SMOOTHENING_FILTER to be defined.
Definition at line 61 of file hierodule_adc.h.
The documentation for this struct was generated from the following file:
/home/ushumgigal/git/hierodule/Inc/hierodule_adc.h